pub mod chat_view;
pub mod chat_view_helpers;
pub mod chat_view_simple;
pub mod history_view;
pub mod keyboard_shortcuts;
pub mod mcp_add_helpers;
pub mod mcp_add_view;
pub mod mcp_configure_helpers;
pub mod mcp_configure_view;
pub mod model_selector;
pub mod model_selector_rows;
pub mod profile_editor_demo;
pub mod profile_editor_demo_sections;
pub mod settings_view;
pub mod settings_view_dispatch;
pub mod settings_view_helpers;
pub mod simple_test;
pub mod theme;

pub use chat_view::ChatViewController;
pub use history_view::HistoryViewController;
pub use mcp_add_view::McpAddViewController;
pub use mcp_configure_view::McpConfigureViewController;
pub use model_selector::ModelSelectorViewController;
pub use profile_editor_demo::ProfileEditorDemoViewController;
pub use settings_view::SettingsViewController;
pub use settings_view::{set_layer_background_color, set_layer_border, set_layer_corner_radius};
pub use theme::{FlippedStackView, Theme};
